import type { Metadata } from "next";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import Right_panel from "@/components/right_panel/right_panel";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="container flex mt-24 justify-between">
          <div className="leftPanel">{children}</div>
          <Right_panel />
        </main>
        <Footer />
      </body>
    </html>
  );
}
